language: node_js
node_js: 10

before_script:
  - npm install firebase-tools -g
  - cd functions
  - npm install
  
script:
  - firebase --non-interactive deploy --only functions --project "$PROJECT_ID" --token "$TOKEN"
